version: '3.1'

services:
  db:
    image: postgres:13.1
    privileged: true
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: Ekaterina
      POSTGRES_PASSWORD: 22
      POSTGRES_DB: db
#  backend:
#    build: ./todo
#    privileged: true
#    ports:
#      - 8080:8080
#    command:
#      bash -c "
#      python manage.py migrate &&
#      python manage.py create_user &&
#      python manage.py create_project_and_todo &&
#      python manage.py runserver 0.0.0.0:8000
#      "
#    depends_on:
#      - db

